{{- if and (not .Values.grafana.externalServices.prometheus.secret.create) (not .Values.grafana.externalServices.loki.secret.create) (not .Values.grafana.externalServices.tempo.secret.create) }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-credentials
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: global-secret-store
    kind: ClusterSecretStore
  target:
    name: grafana-credentials
    creationPolicy: Owner
  data:
  # metrics 
  - secretKey: GRAFANA_METRICS_HOST
    remoteRef:
      key: grafana-cloud-credentials
      property: grafana-metrics-host
  - secretKey: GRAFANA_METRICS_USER
    remoteRef:
      key: grafana-cloud-credentials
      property: grafana-metrics-user
  # logs    
  - secretKey: GRAFANA_LOGS_HOST
    remoteRef:
      key: grafana-cloud-credentials
      property: grafana-logs-host    
  - secretKey: GRAFANA_LOGS_USER
    remoteRef:
      key: grafana-cloud-credentials
      property: grafana-logs-user
  # traces
  - secretKey: GRAFANA_TRACES_HOST
    remoteRef:
      key: grafana-cloud-credentials
      property: grafana-traces-host    
  - secretKey: GRAFANA_TRACES_USER
    remoteRef:
      key: grafana-cloud-credentials
      property: grafana-traces-user
  # toke credential    
  - secretKey: GRAFANA_TOKEN
    remoteRef:
      key: grafana-cloud-credentials
      property: grafana-token
{{- end }}