{{- if and (not .Values.grafana.externalServices.prometheus.secret.create) (not .Values.grafana.externalServices.loki.secret.create) (not .Values.grafana.externalServices.tempo.secret.create) }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: global-secret-store
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
{{- end }}
